name: deploy
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: setup jdk 17
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn -B package --file pom.xml
    - name: deploy to tomcat
    env:
       tomcat_user: ${secrets.uid}
       tomcat_pwd: ${secrets.pwd}
       
      run: curl -v -u -T $tomcat_user:$tomcat_pwd /home/runner/work/etoe/etoe/target/Ecomm.war 'http://13.233.157.82:8080/manager/text/deploy?path=/Ecomm.war'
  
    
      
      
    
   
  
